# Pull Request Labeler Configuration
# This file configures automatic labeling of pull requests based on changed files

documentation:
  - '**/*.md'
  - 'docs/**/*'

tests:
  - '**/tests/**'
  - '**/*test*.py'

python:
  - '**/*.py'
  - '**/requirements.txt'
  - '**/pyproject.toml'

workflows:
  - '.github/workflows/**'

frontend:
  - 'docs/**/*.html'
  - 'docs/**/*.js'
  - 'docs/**/*.json'
