# Pull Request Labeler Configuration
# This file configures automatic labeling of pull requests based on changed files

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
  - changed-files:
    - any-glob-to-any-file: 'docs/**/*'

tests:
  - changed-files:
    - any-glob-to-any-file: '**/tests/**'
  - changed-files:
    - any-glob-to-any-file: '**/*test*.py'

python:
  - changed-files:
    - any-glob-to-any-file: '**/*.py'
  - changed-files:
    - any-glob-to-any-file: '**/requirements.txt'
  - changed-files:
    - any-glob-to-any-file: '**/pyproject.toml'

workflows:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'docs/**/*.html'
  - changed-files:
    - any-glob-to-any-file: 'docs/**/*.js'
  - changed-files:
    - any-glob-to-any-file: 'docs/**/*.json'
